vscode:
  extensions:
    - aaron-bond.better-comments
    - adpyke.codesnap
    - dracula-theme.theme-dracula
    - esbenp.prettier-vscode
    - formulahendry.auto-close-tag
    - formulahendry.auto-rename-tag
    - GitHub.copilot
    - gitpod.gitpod-desktop
    - JuanBlanco.solidity
    - KevinRose.vsc-python-indent
    - laktak.hjson
    - magicstack.MagicPython
    - mechatroner.rainbow-csv
    - mongodb.mongodb-vscode
    - ms-azuretools.vscode-docker
    - MS-CEINTL.vscode-language-pack-tr
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-vscode-remote.remote-containers
    - ms-vscode-remote.remote-ssh
    - ms-vscode-remote.remote-ssh-edit
    - ms-vscode-remote.remote-wsl
    - ms-vscode-remote.vscode-remote-extensionpack
    - ms-vscode.live-server
    - ms-vsliveshare.vsliveshare
    - NoahSyn10.pydoctestbtn
    - PKief.material-icon-theme
    - rangav.vscode-thunder-client
    - ritwickdey.LiveServer
    - samuelcolvin.jinjahtml
    - SonarSource.sonarlint-vscode
    - sourcery.sourcery
    - TabNine.tabnine-vscode
    - zhuangtongfa.material-theme