version: "3.8"

services:

    mongodb:
        container_name: mongodb
        image: mongo:latest
        hostname: akademirobot_mongodb
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: "admin"
            MONGO_INITDB_ROOT_PASSWORD: "sifre"
        volumes:
            - mongodb:/data/db
        networks:
            - network
        restart: always

    mongo-express:
        container_name: mongo-express
        image: mongo-express:latest
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
            ME_CONFIG_MONGODB_ADMINPASSWORD: "sifre"
            ME_CONFIG_MONGODB_SERVER: "mongodb"
            ME_CONFIG_MONGODB_SSLVALIDATE: "false"
        volumes:
            - mongo-express:/data/mongo-express
        networks:
            - network
        restart: unless-stopped

    akademirobot:
        container_name: akademirobot
        build: .
        image: akademirobot:latest
        restart: always
        volumes:
            - 'self:/opt/app/KekikRobot'
        networks:
            - network
        # depends_on:
        #     - mongodb
        # links:
        #     - mongodb

networks:
    network:
        driver: bridge

volumes:
    mongodb:
    mongo-express:
    self: