vscode:
  extensions:
    # Jinja Template Support
    - 000000.jinja2
    - noxiz.jinja-snippets
    - samuelcolvin.jinjahtml
    - wholroyd.jinja
    
    # Code Quality & Formatting
    - aaron-bond.better-comments
    - esbenp.prettier-vscode
    - formulahendry.auto-close-tag
    - formulahendry.auto-rename-tag
    
    # Shell & Script Support
    - foxundermoon.shell-format
    - jeff-hykin.better-shellscript-syntax
    
    # Git & Version Control
    - eamodio.gitlens
    
    # Python Development
    - ms-python.black-formatter
    - ms-python.isort
    - ms-python.python
    - ms-python.vscode-pylance
    
    # C/C++ Development
    - ms-vscode.cpptools
    - ms-vscode.cpptools-extension-pack
    
    # Remote Development
    - ms-vscode-remote.remote-ssh
    - ms-vscode-remote.remote-ssh-edit
    - ms-vscode.remote-explorer
    
    # AI & Productivity
    - github.copilot-chat
    - openai.chatgpt
    
    # Utilities
    - dokca.42-ft-count-line
    - irongeek.vscode-env
    - kejun.devtoys
    - mechatroner.rainbow-csv
    - ms-vscode.live-server
    - yzhang.markdown-all-in-one
    
    # Theme & Icons
    - dracula-theme.theme-dracula
    - pkief.material-icon-theme
    - pkief.material-product-icons
    
    # Language Pack
    - ms-ceintl.vscode-language-pack-tr
